export const properties = [
    {
        title: "Luxury Villa with Ocean Views",
        images: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"],
        price: "₹ 7,500,000",
        propertyType: "Villa",
        configuration: "4 BHK",
        description: "Experience luxury living in this stunning villa, featuring expansive gardens, breathtaking ocean views, and elegant interiors designed for comfort and sophistication.",
        location: "JP Nagar",
        address: {
            city: "Bengaluru",
            state: "Karnataka",
        },
        area: "20,000 Sq. Ft",
        yearBuilt: 2023,
        features: ["Swimming Pool", "Garden", "Private Parking"],
        recommend: false,
    },
    {
        title: "Modern Flat with Prime Amenities",
        images: ["https://plus.unsplash.com/premium_photo-1676823547752-1d24e8597047?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"],
        price: "₹ 5,200,000",
        propertyType: "Flat",
        configuration: "3 BHK",
        description: "Modern flat with excellent amenities and spacious interiors.",
        location: "Whitefield",
        address: {
            city: "Bengaluru",
            state: "Karnataka",
        },
        area: "1,500 Sq. Ft",
        yearBuilt: 2020,
        features: ["Gym Access", "Covered Parking", "Play Area"],
        recommend: false,
    },
    {
        title: "Charming House with Garden",
        images: ["https://plus.unsplash.com/premium_photo-1661908377130-772731de98f6?q=80&w=2012&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"],
        price: "₹ 4,800,000",
        propertyType: "House",
        configuration: "3 BHK",
        description: "Charming house with a beautiful garden and modern amenities.",
        location: "Bengaluru",
        address: {
            city: "Bengaluru",
            state: "Karnataka",
        },
        area: "1,800 Sq. Ft",
        yearBuilt: 2019,
        features: ["Garden", "Garage", "Pet Friendly"],
        recommend: false,
    },
    {
        title: "Grand Villa with Stunning Views",
        images: ["https://plus.unsplash.com/premium_photo-1661908377130-772731de98f6?q=80&w=2012&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"],
        price: "₹ 12,000,000",
        propertyType: "Villa",
        configuration: "5 BHK",
        description: "Luxurious villa with premium amenities and a stunning view.",
        location: "Electronic City",
        address: {
            city: "Bengaluru",
            state: "Karnataka",
        },
        area: "3,500 Sq. Ft",
        yearBuilt: 2023,
        features: ["Swimming Pool", "Terrace", "Private Parking"],
        recommend: false,
    },
    {
        title: "Cozy Flat in Prime Location",
        images: ["https://plus.unsplash.com/premium_photo-1661908377130-772731de98f6?q=80&w=2012&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"],
        price: "₹ 3,500,000",
        propertyType: "Flat",
        configuration: "2 BHK",
        description: "Cozy flat in a prime location with essential amenities.",
        location: "Sarjapur",
        address: {
            city: "Bengaluru",
            state: "Karnataka",
        },
        area: "1,200 Sq. Ft",
        yearBuilt: 2021,
        features: ["Balcony", "24/7 Security", "Basement Parking"],
        recommend: false,
    },
    {
        title: "Elegant House with Modern Design",
        images: ["https://plus.unsplash.com/premium_photo-1661908377130-772731de98f6?q=80&w=2012&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"],
        price: "₹ 9,800,000",
        propertyType: "House",
        configuration: "4 BHK",
        description: "Elegant house with a spacious layout and modern design.",
        location: "HSR Layout",
        address: {
            city: "Bengaluru",
            state: "Karnataka",
        },
        area: "2,200 Sq. Ft",
        yearBuilt: 2022,
        features: ["Garden", "Solar Panels", "Pet Friendly"],
        recommend: false,
    },
    {
        title: "Grand Villa with Luxurious Features",
        images: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"],
        price: "₹ 15,000,000",
        propertyType: "Villa",
        configuration: "6 BHK, 8 Bathrooms",
        description: "Grand villa with luxurious features and ample living space.",
        location: "Kormangla",
        address: {
            city: "Bengaluru",
            state: "Karnataka",
        },
        area: "5,000 Sq. Ft",
        yearBuilt: 2024,
        features: ["Swimming Pool", "Gym", "Home Theatre"],
        recommend: true,
    },
    {
        title: "Beautiful Villa with Luxurious Amenities",
        images: [
            "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
        ],
        price: "₹ 10,000,000",
        propertyType: "Villa",
        description: "Beautiful villa with luxurious amenities and stunning views.",
        location: "Varthuru",
        address: {
            city: "Bengaluru",
            state: "Karnataka",
        },
        area: "3,000 Sq. Ft",
        yearBuilt: 2023,
        features: ["Swimming Pool", "Garage", "Terrace Garden"],
        configuration: "4 BHK",
        recommend: true,
    },
    {
        title: "Al - Jannah Homes",
        images: [
            "https://res.cloudinary.com/dzpastl5k/image/upload/v1731661702/Home2NestGallery/p9ynspjf1rv5fzwsset7.webp",
            "https://res.cloudinary.com/dzpastl5k/image/upload/v1731661703/Home2NestGallery/ormsdavukzkxqxmwowyd.webp",
            "https://res.cloudinary.com/dzpastl5k/image/upload/v1731661705/Home2NestGallery/pz20mjbe7no6hdsywrfb.webp",
            "https://res.cloudinary.com/dzpastl5k/image/upload/v1731661706/Home2NestGallery/htzlj4snjzz4xhausxvz.webp",
            "https://res.cloudinary.com/dzpastl5k/image/upload/v1731661707/Home2NestGallery/wizwnvcreu9odqjh0jmf.webp",
            "https://res.cloudinary.com/dzpastl5k/image/upload/v1731661708/Home2NestGallery/zrw8s7bkrrmzjwpfiitk.webp"
        ],
        price: "₹ 7,500,000",
        propertyType: "House",
        description: "Charming house with a beautiful garden and modern amenities.",
        location: "Carmelaram",
        address: {
            city: "Bengaluru",
            state: "Karnataka",
        },
        area: "1,250 sq.ft",
        yearBuilt: 2023,
        features: ["Parking"],
        configuration: "6 BHK",
        recommend: true,
    }
];

export const interiorDesign = [
    {
        img1: "/interiorDesigns/interior1.webp",
        img2: "/interiorDesigns/interior3.webp",
        img3: "/interiorDesigns/interior5.webp",
        img4: "/interiorDesigns/interior9.webp",
        img5: "/interiorDesigns/interior13.webp",
    },
    {
        img1: "/interiorDesigns/interior2.webp",
        img2: "/interiorDesigns/interior4.webp",
        img3: "/interiorDesigns/interior6.webp",
        img4: "/interiorDesigns/interior8.webp",
        img5: "/interiorDesigns/interior10.webp",
    },
    {
        img1: "/interiorDesigns/interior7.webp",
        img2: "/interiorDesigns/interior11.webp",
        img3: "/interiorDesigns/interior12.webp",
        img4: "/interiorDesigns/interior14.webp",
        img5: "/interiorDesigns/interior15.webp",
    },

]
